### ISSUE TITLE
로그인 / 로그아웃 상태 헤더

### ISSUE THREAD

**Issue by Junow** [connect-foundation/2019-18#135]
로그인 / 로그아웃일때 헤더에 들어갈 아이콘조정이 필요합니다.

ex ) 로그인 상태 -> 검색, 업로드, 알람, 로그아웃, 마이페이지
	 로그아웃 상태 -> 검색, 로그인

**Comment by suphremechicken** [comment]
로그인 -> 검색, 업로드, 알람, 마이포토폴리오
로그아웃 -> 검색, 로그인 
으로 헤더 변경 (( 로그아웃은, 상단 프로필 사진을 클릭했을때 선택가능한 어떤 모달이 나타나는것이 어떤지.. 
상단에 로그아웃 버튼까지 있으면 헤더에 버튼이 너무 많은 느낌.. ))
