### ISSUE TITLE
[Bug] 하트를 눌러도 하트가 안채워지고 숫자만 올라감

### ISSUE THREAD

**Issue by 2ssue** [connect-foundation/2019-18#136]
![image](https://user-images.githubusercontent.com/42017052/70299666-e35d5000-1838-11ea-92ef-fe1358df9c4e.png)

하트를 누르면 숫자는 올라가는데 옆에 하트가 클릭된거처럼 표시가 안돼요!
UX상의 버그인 것 같습니다..

**Comment by changicho** [comment]
처음부터 10개의 하트가 있는것도 0개로 수정해주세요! 세상이 얼마나 각박한데요

**Comment by Junow** [comment]
해당기능은 삭제되었습니다. 감사합니다. 😄
