### ISSUE TITLE
[Bug] 로그인을 하지 않아도 업로드 창에 들어 가짐

### ISSUE THREAD

**Issue by GiPyoo** [connect-foundation/2019-18#143]
이 기능을 의도한지는 모르겠지만 로그인을 하지 않았을 때 업로드를 누르면 업로드 참으로 넘어가집니다.

그리고 업로드를 실행하면 로그인 문제인지 등록이 되지 않습니다.

**Comment by suphremechicken** [comment]
로그인하지 않았을때 업로드 창으로 이동하지 못하도록 수정하겠습니다.
