### ISSUE TITLE
[Bug] 모바일로 들어가면 화면이 깨져요

### ISSUE THREAD

**Issue by Johnie-Yeo** [connect-foundation/2019-18#144]
왼쪽부분은 아예 나오지 않습니다. 헤더부분도 겹치고 깨지고요
![Screenshot from 2019-12-06 15-23-42](https://user-images.githubusercontent.com/39961261/70301020-85cb0280-183c-11ea-9b95-b15957cd8299.png)

**Comment by Junow** [comment]
현재 모바일 버전은 고려중이지 않습니다. 감사합니다. 😄
