### ISSUE TITLE
[enhancement] 회원가입에서 다른 페이지로의 이동

### ISSUE THREAD

**Issue by sukjae** [connect-foundation/2019-18#146]
### 기능 요약

로그인 페이지에서 -> 회원가입 페이지로 이동 후 다른 페이지로의 이동 기능

### 기능 배경

홈페이지 -> 로그인 -> 회원가입으로 이동 후에 
다른 페이지로 전환이 어렵습니다. 

### 원하는 결과

![Screen Shot 2019-12-06 at 3 37 36 PM](https://user-images.githubusercontent.com/8156543/70301721-7e0c5d80-183e-11ea-8a3e-fad4320405fc.png)

### 원하는 결과를 위한 방법 제시

링크를 추가합니다.

**Comment by suphremechicken** [comment]
감사합니다
