### ISSUE TITLE
[bug] 하트가 10개부터 시작합니다. 

### ISSUE THREAD

**Issue by sukjae** [connect-foundation/2019-18#161]
### 어떤 버그가 존재하나요?

댓글을 작성하면, 좋아요가 10개에서 시작합니다.

### 기대했던 결과

댓글을 작성하면, 좋아요가 0개에서 시작

### 버그 재현 방법

1. 사진을 누릅니다
2. 댓글을 작성합니다

### 추가 정보 (선택)

![image](https://user-images.githubusercontent.com/8156543/70772694-ab19bc80-1db8-11ea-9390-657db2e93c09.png)

**Comment by Junow** [comment]
해당기능은 삭제되었습니다. 감사합니다. 😄
