### ISSUE TITLE
[bug] 소켓 연결에 문제가 있는듯 합니다

### ISSUE THREAD

**Issue by sukjae** [connect-foundation/2019-18#167]
### 어떤 버그가 존재하나요?

소켓 연결을 무한 반복하는것 같습니다. 

### 기대했던 결과

한두번 시도 후 소켓 연결 시도를 중단합니다.

#### Desktop (아래 정보를 기재해 주세요):

 - OS: OSX 10.15.1 
 - Browser chrome
 - Version 78.0.3904.108

### 버그 재현 방법

1. 메인화면에 들어갑니다.
2. 로그인을 합니다
3. 상품을 둘러봅니다

### 추가 정보 (선택)

![image](https://user-images.githubusercontent.com/8156543/70773278-59723180-1dba-11ea-9322-81b60013fe2a.png)

**Comment by 2ssue** [comment]
![image](https://user-images.githubusercontent.com/42017052/70773992-524c2300-1dbc-11ea-902e-d8b8f4fc5eb9.png)

탐방하는 동안 에러가 133개가 쌓였습니다..!

**Comment by Junow** [comment]
해결하였습니다. 감사합니다. 😄
