### ISSUE TITLE
처음에 이미지가 로딩 중일 때, 바둑판 모양으로 렌더링이 됐다가 정상으로 돌아옵니다

### ISSUE THREAD

**Issue by 2ssue** [connect-foundation/2019-18#168]
![image](https://user-images.githubusercontent.com/42017052/70773273-537c5080-1dba-11ea-8d55-6354decdede4.png)

처음에 이미지가 바둑판 모양처럼 됐다가 정상적으로 보여져서, 마치 렉걸리는 것처럼 보여요.
처음부터 꽉찬 이미지로 떴으면 좋겠어욤

**Comment by Junow** [comment]
어떤부분을 어떻게 개선해야 할지 모르겠네요.. 혹시 아이디어가 있다면 공유 부탁드립니다. 😢

**Comment by Junow** [comment]
해결하였습니다. 감사합니다. 😄
