### ISSUE TITLE
[Bug]업로드 버그

### ISSUE THREAD

**Issue by kyungrae** [connect-foundation/2019-18#170]
디자인, 일러스트 분야 카테고리로 업로드가 불가능합니다.

![18조](https://user-images.githubusercontent.com/26711771/70774149-bd95f500-1dbc-11ea-82b9-1d389300370e.png)

**Comment by jominjimail** [comment]
업로드 자체에 버그가 잇었음

**Comment by jominjimail** [comment]
FIXED
